#!name=Qmai Modify Card Level
#!desc=企迈小程序系统修改会员卡等级 (Shadowrocket版)
#!author=qinxi
#!system=ios

[MITM]
hostname = %APPEND% webapi.qmai.cn

[Script]
# 标准响应体修改，需带上 requires-body=1
Qmai_Card_Level = type=http-response, pattern=^https:\/\/webapi\.qmai\.cn\/web, requires-body=1, max-size=3145728, script-path=https://raw.githubusercontent.com/qinxi/script/master/quantumult-x/scripts/qmai_card_level.js